trigger:
- main

pool:
  name: Default   # your self-hosted agent

steps:

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest

- script: echo "Docker image build completed"