apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtc-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtc-db
  template:
    metadata:
      labels:
        app: rtc-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: rtc
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rtc-db
spec:
  selector:
    app: rtc-db
  ports:
  - port: 5432
    targetPort: 5432
